SELECT
    P.NAME AS PRODUCT_NAME,
    ROUND(SUM(OI.SALE_PRICE),
    2) AS TOTAL_SALES
FROM
    BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.ORDER_ITEMS AS OI
    JOIN BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.PRODUCTS AS P
    ON OI.PRODUCT_ID = P.ID
GROUP BY
    PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC LIMIT 15;