SELECT
    U.ID AS USER_ID,
    U.FIRST_NAME,
    U.LAST_NAME,
    ROUND(SUM(OI.SALE_PRICE),
    2) AS LIFETIME_VALUE
FROM
    BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.USERS AS U
    JOIN BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.ORDER_ITEMS AS OI
    ON U.ID = OI.USER_ID
GROUP BY
    USER_ID,
    FIRST_NAME,
    LAST_NAME
ORDER BY
    LIFETIME_VALUE DESC LIMIT 10;