SELECT
    FORMAT_DATE('%Y-%m',
    O.CREATED_AT) AS MONTH,
    ROUND(SUM(OI.SALE_PRICE) / COUNT(DISTINCT O.ORDER_ID),
    2) AS AVG_ORDER_VALUE
FROM
    `BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.ORDERS` AS O
    JOIN `BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.ORDER_ITEMS` AS OI
    ON O.ORDER_ID = OI.ORDER_ID
GROUP BY
    MONTH
ORDER BY
    MONTH;