SELECT
    P.CATEGORY,
    ROUND(SUM(OI.SALE_PRICE),
    2) AS REVENUE,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS
FROM
    BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.PRODUCTS AS P
    JOIN BIGQUERY-PUBLIC-DATA.THELOOK_ECOMMERCE.ORDER_ITEMS AS OI
    ON P.ID = OI.PRODUCT_ID
GROUP BY
    CATEGORY
ORDER BY
    REVENUE DESC LIMIT 10