SELECT
    YEAR,
    TOTAL_SALES,
    ROUND( (TOTAL_SALES - LAG(TOTAL_SALES) OVER (ORDER BY YEAR)) / LAG(TOTAL_SALES) OVER (ORDER BY YEAR) * 100,
    2 ) AS GROWTH_PERCENT
FROM
    (
        SELECT
            EXTRACT(YEAR FROM DATE) AS YEAR,
            ROUND(SUM(SALE_DOLLARS),
            2) AS TOTAL_SALES
        FROM
            BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES
        GROUP BY
            YEAR
    )
ORDER BY
    YEAR DESC