WITH LATEST_YEAR AS (
  SELECT
    MAX(EXTRACT(YEAR FROM DATE)) AS YEAR
  FROM
    BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES
)
SELECT
  STORE_NAME,
  ROUND(SUM(SALE_DOLLARS),
  1) AS TOTAL_SALES_IN_DOLLARS
FROM
  BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES,
  LATEST_YEAR
WHERE
  EXTRACT(YEAR FROM DATE) = LATEST_YEAR.YEAR
GROUP BY
  STORE_NAME
ORDER BY
  TOTAL_SALES_IN_DOLLARS DESC LIMIT 15;