WITH TOP_COUNTIES AS (
  SELECT
    COUNTY,
    SUM(SALE_DOLLARS) AS TOTAL_SALES
  FROM
    `BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES`
  GROUP BY
    COUNTY
  ORDER BY
    TOTAL_SALES DESC LIMIT 5
)
SELECT
  COUNTY,
  EXTRACT(YEAR FROM DATE) AS YEAR,
  EXTRACT(MONTH FROM DATE) AS MONTH,
  ROUND(SUM(SALE_DOLLARS),
  1) AS MONTHLY_SALES
FROM
  `BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES`
WHERE
  COUNTY IN (
    SELECT
      COUNTY
    FROM
      TOP_COUNTIES
  )
GROUP BY
  COUNTY,
  YEAR,
  MONTH
ORDER BY
  YEAR,
  MONTH,
  MONTHLY_SALES DESC;