WITH YEARLY_SALES AS (
    SELECT
        COUNTY,
        EXTRACT(YEAR FROM DATE) AS YEAR,
        SUM(SALE_DOLLARS) AS TOTAL_SALES
    FROM
        BIGQUERY-PUBLIC-DATA.IOWA_LIQUOR_SALES.SALES
    GROUP BY
        COUNTY,
        YEAR
), GROWTH AS (
    SELECT
        COUNTY,
        YEAR,
        TOTAL_SALES,
        ROUND((TOTAL_SALES - LAG(TOTAL_SALES) OVER (PARTITION BY COUNTY ORDER BY YEAR) / LAG(TOTAL_SALES) OVER (PARTITION BY COUNTY ORDER BY YEAR) * 100),
        1) AS YOY_GROWTH
    FROM
        YEARLY_SALES
)
SELECT
    *
FROM
    GROWTH
WHERE
    YOY_GROWTH IS NOT NULL
    AND COUNTY IS NOT NULL
ORDER BY
    YOY_GROWTH DESC LIMIT 15;