SELECT
    DATE,
    ROUND(AVG(NEW_CONFIRMED) OVER (ORDER BY DATE ROWS BETWEEN 6 PRECEDING
    AND CURRENT ROW),
    2) AS AVG_NEW_CASES_7D
FROM
    `BIGQUERY-PUBLIC-DATA.COVID19_OPEN_DATA.COVID19_OPEN_DATA`
WHERE
    COUNTRY_NAME = 'United States'
ORDER BY
    DATE;