WITH MONTHLY_TOTALS AS (
    SELECT
        COUNTRY_NAME,
        FORMAT_DATE('%Y-%m',
        DATE) AS MONTH,
        SUM(NEW_CONFIRMED) AS MONTHLY_CASES
    FROM
        `BIGQUERY-PUBLIC-DATA.COVID19_OPEN_DATA.COVID19_OPEN_DATA`
    WHERE
        COUNTRY_NAME IN ('United States of America', 'India', 'Brazil', 'Russia', 'Philippines')
    GROUP BY
        COUNTRY_NAME,
        MONTH
)
SELECT
    COUNTRY_NAME,
    MONTH,
    MONTHLY_CASES,
    LAG(MONTHLY_CASES) OVER (PARTITION BY COUNTRY_NAME ORDER BY MONTH) AS PREV_MONTH_CASES,
    ROUND( SAFE_DIVIDE(MONTHLY_CASES - LAG(MONTHLY_CASES) OVER (PARTITION BY COUNTRY_NAME ORDER BY MONTH),
    LAG(MONTHLY_CASES) OVER (PARTITION BY COUNTRY_NAME ORDER BY MONTH)) * 100,
    2 ) AS GROWTH_RATE
FROM
    MONTHLY_TOTALS
ORDER BY
    COUNTRY_NAME,
    MONTH;