SELECT
    COUNTRY_NAME,
    SUM(NEW_CONFIRMED) AS TOTAL_CASES,
    SUM(NEW_DECEASED) AS TOTAL_DEATHS,
    ROUND(SUM(NEW_DECEASED) / SUM(NEW_CONFIRMED) * 100,
    2) AS FATALITY_RATE
FROM
    `BIGQUERY-PUBLIC-DATA.COVID19_OPEN_DATA.COVID19_OPEN_DATA`
WHERE
    NEW_CONFIRMED > 0
GROUP BY
    COUNTRY_NAME
HAVING
    TOTAL_CASES > 100000
ORDER BY
    FATALITY_RATE DESC LIMIT 10;