WITH DAILY AS (
  SELECT
    COUNTRY_NAME,
    DATE,
    SUM(NEW_CONFIRMED) AS DAILY_CASES
  FROM
    `BIGQUERY-PUBLIC-DATA.COVID19_OPEN_DATA.COVID19_OPEN_DATA`
  WHERE
    COUNTRY_NAME IN ('Philippines', 'United States', 'India', 'Brazil', 'Russia')
  GROUP BY
    COUNTRY_NAME,
    DATE
), PEAKS AS (
  SELECT
    COUNTRY_NAME,
    MAX(DAILY_CASES) AS PEAK_CASES
  FROM
    DAILY
  GROUP BY
    COUNTRY_NAME
), POST_PEAK AS (
  SELECT
    D.COUNTRY_NAME,
    D.DATE,
    D.DAILY_CASES,
    P.PEAK_CASES,
    100 * SAFE_DIVIDE(D.DAILY_CASES,
    P.PEAK_CASES) AS PCT_OF_PEAK
  FROM
    DAILY D
    JOIN PEAKS P
    USING (COUNTRY_NAME)
  WHERE
    D.DAILY_CASES < P.PEAK_CASES
)
SELECT
  COUNTRY_NAME,
  DATE,
  DAILY_CASES,
  ROUND(PCT_OF_PEAK,
  2) AS PCT_OF_PEAK
FROM
  POST_PEAK
WHERE
  PCT_OF_PEAK < 50
ORDER BY
  COUNTRY_NAME,
  DATE;