WITH TRIPS_BY_STATION_HOUR AS (
  SELECT
    START_STATION_ID,
    START_STATION_NAME,
    EXTRACT(HOUR FROM START_TIME) AS HOUR_OF_DAY,
    COUNT(*) AS TRIPS_COUNT
  FROM
    `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS`
  WHERE
    START_STATION_ID IS NOT NULL
  GROUP BY
    START_STATION_ID,
    START_STATION_NAME,
    HOUR_OF_DAY
),
 -- compute total trips per station so we can compute percent share
STATION_TOTALS AS (
  SELECT
    START_STATION_ID,
    START_STATION_NAME,
    SUM(TRIPS_COUNT) AS STATION_TOTAL_TRIPS
  FROM
    TRIPS_BY_STATION_HOUR
  GROUP BY
    START_STATION_ID,
    START_STATION_NAME
),
 -- join and use window function to pick the peak hour per station
RANKED_PEAKS AS (
  SELECT
    T.START_STATION_ID,
    T.START_STATION_NAME,
    T.HOUR_OF_DAY,
    T.TRIPS_COUNT,
    SAFE_DIVIDE(T.TRIPS_COUNT,
    S.STATION_TOTAL_TRIPS) AS PCT_OF_STATION_TRIPS,
    ROW_NUMBER() OVER (PARTITION BY T.START_STATION_ID ORDER BY T.TRIPS_COUNT DESC,
    T.HOUR_OF_DAY) AS RN
  FROM
    TRIPS_BY_STATION_HOUR T
    JOIN STATION_TOTALS S
    USING (START_STATION_ID,
    START_STATION_NAME)
)
SELECT
  START_STATION_ID,
  START_STATION_NAME,
  HOUR_OF_DAY AS PEAK_HOUR,
  TRIPS_COUNT AS PEAK_HOUR_TRIPS,
  ROUND(PCT_OF_STATION_TRIPS * 100,
  2) AS PCT_OF_STATION_TRIPS_PCT
FROM
  RANKED_PEAKS
WHERE
  RN = 1
ORDER BY
  PEAK_HOUR_TRIPS DESC LIMIT 100;