-- Approximate median trip duration (in minutes) per subscriber type
WITH DURATIONS AS (
  SELECT
    SUBSCRIBER_TYPE, -- or 'usertype' depending on your schema
    CAST(DURATION_MINUTES AS FLOAT64) AS DURATION_MINUTES
  FROM
    `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS`
  WHERE
    DURATION_MINUTES IS NOT NULL
), MEDIAN_BY_SUBSCRIBER AS (
  SELECT
    SUBSCRIBER_TYPE,
 
    -- APPROX_QUANTILES returns an ARRAY; index with [OFFSET(n)]
    -- here we request 100 quantiles and take the 50th percentile (approx median)
    APPROX_QUANTILES(DURATION_MINUTES,
    100)[OFFSET(50)] AS APPROX_MEDIAN_MINUTES
  FROM
    DURATIONS
  GROUP BY
    SUBSCRIBER_TYPE
),
 -- average duration per start station, filtered to stations with enough samples
STATION_AVG AS (
  SELECT
    START_STATION_ID,
    START_STATION_NAME,
    COUNT(*) AS TRIPS_AT_STATION,
    AVG(CAST(DURATION_MINUTES AS FLOAT64)) AS AVG_DURATION
  FROM
    `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS`
  WHERE
    DURATION_MINUTES IS NOT NULL
    AND START_STATION_ID IS NOT NULL
  GROUP BY
    START_STATION_ID,
    START_STATION_NAME
  HAVING
    COUNT(*) >= 200 -- ensure statistical significance (adjust threshold)
)
SELECT
  M.SUBSCRIBER_TYPE,
  ROUND(M.APPROX_MEDIAN_MINUTES,
  2) AS MEDIAN_DURATION_MINUTES,
  S.START_STATION_ID,
  S.START_STATION_NAME,
  ROUND(S.AVG_DURATION,
  2) AS STATION_AVG_DURATION,
  S.TRIPS_AT_STATION
FROM
  MEDIAN_BY_SUBSCRIBER M
  CROSS JOIN (
    SELECT
      *
    FROM
      STATION_AVG
    ORDER BY
      AVG_DURATION DESC LIMIT 10
  ) S
WHERE
  M.SUBSCRIBER_TYPE IS NOT NULL
ORDER BY
  M.SUBSCRIBER_TYPE,
  STATION_AVG_DURATION DESC;