WITH ROUTES AS (
    SELECT
        START_STATION_ID,
        START_STATION_NAME,
        END_STATION_ID,
        END_STATION_NAME,
        COUNT(*) AS TOTAL_TRIPS
    FROM
        `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS`
    WHERE
        START_STATION_ID IS NOT NULL
        AND END_STATION_ID IS NOT NULL
    GROUP BY
        START_STATION_ID,
        START_STATION_NAME,
        END_STATION_ID,
        END_STATION_NAME
), TOP_ROUTES AS (
    SELECT
        *
    FROM
        ROUTES
    ORDER BY
        TOTAL_TRIPS DESC LIMIT 25
), MONTHLY_COUNTS AS (
    SELECT
        R.START_STATION_ID,
        R.END_STATION_ID,
        FORMAT_DATE('%Y-%m',
        DATE(START_TIME)) AS YM,
        COUNT(*) AS TRIPS_IN_MONTH
    FROM
        `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS` T
        JOIN TOP_ROUTES R
        ON T.START_STATION_ID = R.START_STATION_ID
        AND T.END_STATION_ID = R.END_STATION_ID
    GROUP BY
        R.START_STATION_ID,
        R.END_STATION_ID,
        YM
)
SELECT
    TR.START_STATION_NAME,
    TR.END_STATION_NAME,
    MC.YM AS MONTH,
    MC.TRIPS_IN_MONTH
FROM
    MONTHLY_COUNTS MC
    JOIN TOP_ROUTES TR
    ON MC.START_STATION_ID = TR.START_STATION_ID
    AND MC.END_STATION_ID = TR.END_STATION_ID
ORDER BY
    TR.TOTAL_TRIPS DESC,
    MC.YM;