WITH DAILY_STATION AS (
  SELECT
    START_STATION_ID,
    START_STATION_NAME,
    DATE(START_TIME) AS DAY,
    COUNT(*) AS DAILY_TRIPS
  FROM
    `BIGQUERY-PUBLIC-DATA.AUSTIN_BIKESHARE.BIKESHARE_TRIPS`
  WHERE
    START_STATION_ID IS NOT NULL
    AND START_TIME IS NOT NULL
  GROUP BY
    START_STATION_ID,
    START_STATION_NAME,
    DAY
), MOVING_AVG AS (
  SELECT
    START_STATION_ID,
    START_STATION_NAME,
    DAY,
    DAILY_TRIPS,
    ROUND( AVG(DAILY_TRIPS) OVER ( PARTITION BY START_STATION_ID ORDER BY DAY ROWS BETWEEN 27 PRECEDING
    AND 1 PRECEDING ),
    2 ) AS MOVING_AVG_28_BEFORE
  FROM
    DAILY_STATION
)
SELECT
  START_STATION_ID,
  START_STATION_NAME,
  DAY,
  DAILY_TRIPS,
  MOVING_AVG_28_BEFORE,
  CASE
    WHEN MOVING_AVG_28_BEFORE IS NULL THEN
      'insufficient_history'
    WHEN SAFE_DIVIDE(DAILY_TRIPS, MOVING_AVG_28_BEFORE) >= 1.5 THEN
      'spike'
    WHEN SAFE_DIVIDE(DAILY_TRIPS, MOVING_AVG_28_BEFORE) <= 0.5 THEN
      'drop'
    ELSE
      'normal'
  END AS ANOMALY_FLAG,
  ROUND(SAFE_DIVIDE(DAILY_TRIPS,
  MOVING_AVG_28_BEFORE),
  2) AS MULTIPLIER
FROM
  MOVING_AVG
WHERE
  MOVING_AVG_28_BEFORE IS NOT NULL -- if you want only rows with history; else remove
ORDER BY
  DAY DESC,
  START_STATION_NAME LIMIT 200;